[package]
name = "tracing-recipes"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "registry"] }
